"""Measure the original recordings for runtime mixing; never writes audio assets.

Requires numpy and ffmpeg. Emits compact, deterministic metadata used by every
peer: EBU R128 loudness and bar-wise chroma/energy for choosing transition cues.
"""
from pathlib import Path
import json
import hashlib
import re
import subprocess
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SCORES = [('harbor.wav',82,4), ('sunlit_fields.ogg',92,4),
          ('trade_winds.ogg',84,4), ('lantern_water.ogg',64,4),
          ('voyager_waltz.ogg',86,3)]
SR = 22050

def analyze(filename, bpm, beats):
    source = ROOT / 'assets/audio' / filename
    loudness = subprocess.run(['ffmpeg','-hide_banner','-i',str(source),'-af','ebur128',
                              '-f','null','-'],capture_output=True,text=True,check=True).stderr
    integrated = float(re.findall(r'I:\s+(-?[\d.]+) LUFS',loudness)[-1])
    raw = subprocess.check_output(['ffmpeg','-v','error','-i',str(source),'-f','f32le',
                                   '-ac','1','-ar',str(SR),'-'])
    pcm = np.frombuffer(raw,dtype='<f4')
    size=8192
    freq=np.fft.rfftfreq(size,1/SR)
    valid=(freq>=65)&(freq<=2100)
    pitch=np.rint(69+12*np.log2(np.maximum(freq,1)/440)).astype(int)%12
    window=np.hanning(size)
    bars=[]
    for start in np.arange(0,len(pcm)/SR,60/bpm*beats):
        segment=pcm[round(start*SR):round((start+60/bpm*beats)*SR)]
        chroma=np.zeros(12)
        for offset in range(0,max(1,len(segment)-size+1),size//2):
            frame=segment[offset:offset+size]
            frame=np.pad(frame,(0,size-len(frame)))
            magnitude=np.abs(np.fft.rfft(frame*window))
            # Compressed magnitudes retain quiet fundamental tones.
            chroma+=np.bincount(pitch[valid],weights=magnitude[valid]**.7,minlength=12)
        chroma/=max(np.linalg.norm(chroma),1e-12)
        bars.append({'chroma':np.round(chroma,5).tolist(),
                     'rms':round(float(np.sqrt(np.mean(segment**2))),5)})
    return {'sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'lufs':integrated,'gain_db':round(-18.0-integrated,2),'bars':bars}

if __name__=='__main__':
    data=[analyze(*spec) for spec in SCORES]
    output='class_name CatanSoundtrackAnalysis\nextends RefCounted\n\n'
    output+='# Generated by tools/analyze_soundtrack.py from unmodified source audio.\n'
    output+='const DATA='+json.dumps(data,separators=(',',':'))+'\n'
    (ROOT/'scripts/soundtrack_analysis.gd').write_text(output)
    print('Measured LUFS:',[row['lufs'] for row in data])
